name: Release

on:
  push:
    tags:
      - "v*"
      - "test-v*"
  pull_request:

permissions: write-all

env:
  UBUNTU_CODENAME: mantic
  UBUNTU_VERSION: "23.10"
  NERDCTL_VERSION: "1.7.0"
  FLANNEL_VERSION: "1.2.0"
  BINFMT_VERSION: "deploy/v7.0.0-28"
  BINFMT_QEMU_VERSION: "7.0.0" 

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Download cloud images
        run: |
          make cloud-images UBUNTU_CODENAME=${UBUNTU_CODENAME} UBUNTU_VERSION=${UBUNTU_VERSION}

      - name: Download binfmt
        run: |
          make binfmt BINFMT_VERSION=${BINFMT_VERSION} BINFMT_QEMU_VERSION=${BINFMT_QEMU_VERSION}

      - name: Download containerd dependencies
        run: |
          make containerd NERDCTL_VERSION=${NERDCTL_VERSION} FLANNEL_VERSION=${FLANNEL_VERSION}

      - name: Create release
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Note "folded" style; requires a blank line to insert actual newline
        run: >
          tag="${GITHUB_REF##*/}"

          gh release create "${tag}" --draft --title "${tag}"
          dist/img/ubuntu-${UBUNTU_VERSION}-minimal-cloudimg-amd64.img
          dist/img/ubuntu-${UBUNTU_VERSION}-minimal-cloudimg-amd64.img.sha512sum
          dist/img/ubuntu-${UBUNTU_VERSION}-minimal-cloudimg-arm64.img
          dist/img/ubuntu-${UBUNTU_VERSION}-minimal-cloudimg-arm64.img.sha512sum
          dist/containerd/containerd-utils-amd64.tar.gz
          dist/containerd/containerd-utils-amd64.tar.gz.sha512sum
          dist/containerd/containerd-utils-arm64.tar.gz
          dist/containerd/containerd-utils-arm64.tar.gz.sha512sum
          dist/binfmt/binfmt-amd64.tar.gz
          dist/binfmt/binfmt-amd64.tar.gz.sha512sum
          dist/binfmt/binfmt-arm64.tar.gz
          dist/binfmt/binfmt-arm64.tar.gz.sha512sum
  